### ISSUE TITLE
Links in Wiki are broken

### ISSUE THREAD

**Issue by bmarcote** [jradcliffe5/VLBI_pipeline#6]
Hi Jack,
In the Wiki, all links that take you to the different pipeline steps seem to be broken (all other ones are OK).
When clicking in any of those links (from step 0 to 10) it goes to the same page, and only a message of 

> You do not have permission to update this wiki.

is shown.

**Comment by jradcliffe5** [comment]
Sorry yes, this is because they don't exist yet. I'm planning on getting all the documentation down by the end of the year in prep for a first full release. I'll add a disclaimer into the wiki.

**Comment by kelvinwandia** [comment]
Sorry, I know the issue has already been raised and its still open but the links are still broken

**Comment by jradcliffe5** [comment]
Yep sorry the pages don't exist still. It's on my to-do list but teaching duties got in the way. If you need a hand just send me a message directly for the moment :)

**Comment by jradcliffe5** [comment]
Taken a year and an half but the wiki is mostly populated now @bmarcote !
